import java.util.ArrayList;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
public class GUI extends javax.swing.JFrame {
    ArrayList<Transaction> Transaction = new ArrayList<>();
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ResetBtn = new javax.swing.JButton();
        NameTF = new javax.swing.JTextField();
        PhoneTF = new javax.swing.JTextField();
        ICTF = new javax.swing.JTextField();
        AddressTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        FromValue = new javax.swing.JTextField();
        ToValue = new javax.swing.JTextField();
        FromCurrency = new javax.swing.JComboBox<>();
        ToCurrency = new javax.swing.JComboBox<>();
        AddTransactionBtn = new javax.swing.JButton();
        DisplayTransactionBtn = new javax.swing.JButton();
        SaveTransactionBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        SearchBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        DisplayTodaysTransactionBtn = new javax.swing.JButton();
        DisplayAllTransactionBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        searchnum = new javax.swing.JTextField();
        deletenum = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayTA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Transaction");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Customer");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Name");

        jLabel4.setText("Phone Number");

        jLabel5.setText("IC/Passport Number");

        jLabel6.setText("Address");

        ResetBtn.setText("Reset Customer");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });

        NameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTFActionPerformed(evt);
            }
        });

        PhoneTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneTFActionPerformed(evt);
            }
        });

        ICTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ICTFActionPerformed(evt);
            }
        });

        AddressTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameTF)
                            .addComponent(PhoneTF)
                            .addComponent(ICTF, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                            .addComponent(AddressTF)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ResetBtn)))
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PhoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ICTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(AddressTF, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ResetBtn)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Currency Converter");

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setText("Enter Value");

        jLabel9.setText("Converted Value");

        FromValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromValueActionPerformed(evt);
            }
        });

        ToValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToValueActionPerformed(evt);
            }
        });

        FromCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "RM", "Rupiah" }));
        FromCurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromCurrencyActionPerformed(evt);
            }
        });

        ToCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "RM", "Rupiah" }));
        ToCurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToCurrencyActionPerformed(evt);
            }
        });

        AddTransactionBtn.setText("Add Transaction");
        AddTransactionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTransactionBtnActionPerformed(evt);
            }
        });

        DisplayTransactionBtn.setText("Display Transaction");
        DisplayTransactionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayTransactionBtnActionPerformed(evt);
            }
        });

        SaveTransactionBtn.setText("Save Transaction");
        SaveTransactionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveTransactionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FromValue, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(ToValue))
                        .addGap(56, 56, 56))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AddTransactionBtn)
                        .addGap(33, 33, 33)
                        .addComponent(DisplayTransactionBtn)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FromCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ToCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(SaveTransactionBtn)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(FromValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FromCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ToValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ToCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddTransactionBtn)
                    .addComponent(DisplayTransactionBtn)
                    .addComponent(SaveTransactionBtn))
                .addGap(33, 33, 33))
        );

        jLabel10.setText("Search by phone number");

        jLabel11.setText("Delete the following record, entered phone number");

        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        DisplayTodaysTransactionBtn.setText("Display today's transaction");
        DisplayTodaysTransactionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayTodaysTransactionBtnActionPerformed(evt);
            }
        });

        DisplayAllTransactionBtn.setText("Display all transaction");
        DisplayAllTransactionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayAllTransactionBtnActionPerformed(evt);
            }
        });

        ClearBtn.setText("Clear Transaction");
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });

        DisplayTA.setColumns(20);
        DisplayTA.setRows(5);
        jScrollPane1.setViewportView(DisplayTA);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(416, 416, 416)
                        .addComponent(DisplayTodaysTransactionBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(5, 5, 5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ClearBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deletenum, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)
                                .addComponent(DisplayAllTransactionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(368, 368, 368))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(searchnum, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DeleteBtn)
                            .addComponent(SearchBtn))))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchBtn)
                            .addComponent(DisplayTodaysTransactionBtn)
                            .addComponent(searchnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(DeleteBtn)
                            .addComponent(DisplayAllTransactionBtn)
                            .addComponent(deletenum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)))
                .addComponent(ClearBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        // TODO add your handling code here:
                NameTF.setText("");
		PhoneTF.setText("");
		ICTF.setText("");
		AddressTF.setText("");
		FromValue.setText("00.00");
		ToValue.setText("00.00");
		FromCurrency.setSelectedIndex(0);
		ToCurrency.setSelectedIndex(0);
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void NameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTFActionPerformed

    private void PhoneTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneTFActionPerformed

    private void ICTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ICTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ICTFActionPerformed

    private void AddressTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressTFActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
        boolean found=false;
		while(!found){
			for(Transaction t: Transaction){
				if(t.getPhone().equals(searchnum.getText())){
					DisplayTA.setText(t.toString());
					found=true;
					break;
				}
			}
		}
		if(found==false){
			JOptionPane.showMessageDialog(null,"Transaction not found","Error!",JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
        boolean found=false;
		while(!found){
			for(Transaction t: Transaction){
				if(t.getPhone().equals(deletenum.getText())){
					DisplayTA.setText(t.toString());
					found=true;
                                        Transaction.remove(t);
					break;
				}
			}
		}
		if(found==false){
			JOptionPane.showMessageDialog(null,"Transaction not found","Error!",JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void FromValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FromValueActionPerformed

    private void ToValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToValueActionPerformed

    private void FromCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromCurrencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FromCurrencyActionPerformed

    private void ToCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToCurrencyActionPerformed
        // TODO add your handling code here:
        try{
			String name=(String)NameTF.getText();
			String phone=(String)PhoneTF.getText();
			String ID=(String)ICTF.getText();
			String address=(String)AddressTF.getText();
			String fromC = (String)FromCurrency.getSelectedItem();
			String toC = (String)ToCurrency.getSelectedItem();
			double from = Double.parseDouble(FromValue.getText());
			
			if(from<0){
				throw new Exception();
			}
			Transaction transaction = new Transaction(name,phone,ID,address,fromC,toC,from);
			ToValue.setText(String.format("%.4f",transaction.setConvertedValue()));
		}
		catch(NumberFormatException e){
			JOptionPane.showMessageDialog(null,"Error: Enter valid integer ONLY!","Message",JOptionPane.INFORMATION_MESSAGE);
		}
		catch(Exception e){
			JOptionPane.showMessageDialog(null,"Value should be more than 0","Error!",JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_ToCurrencyActionPerformed

    private void AddTransactionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTransactionBtnActionPerformed
        // TODO add your handling code here:
        try{
			if(NameTF.getText().isEmpty()||PhoneTF.getText().isEmpty()||ICTF.getText().isEmpty()||AddressTF.getText().isEmpty()||FromCurrency.getSelectedItem()==null||ToCurrency.getSelectedItem()==null||FromValue.getText().isEmpty()){
				throw new Exception();
			}
			String name=NameTF.getText();
			String phone=PhoneTF.getText();
			String ID=ICTF.getText();
			String address=AddressTF.getText();
			String fromC=(String)FromCurrency.getSelectedItem();
			String toC=(String)ToCurrency.getSelectedItem();
			double from=Double.parseDouble(FromValue.getText());
			double to=Double.parseDouble(ToValue.getText());
						
			Transaction.add(new Transaction(name,phone,ID,address,fromC,toC,from));
			JOptionPane.showMessageDialog(null,"Added to Array List");
		}
		catch(Exception e){
			JOptionPane.showMessageDialog(null,"Error : Enter valid data","Error",JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_AddTransactionBtnActionPerformed

    private void DisplayTransactionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayTransactionBtnActionPerformed
        // TODO add your handling code here:
        String name=(String)NameTF.getText();
		String phone=(String)PhoneTF.getText();
		String ID=(String)ICTF.getText();
		String address=(String)AddressTF.getText();
		String fromC = (String)FromCurrency.getSelectedItem();
		String toC = (String)ToCurrency.getSelectedItem();
		double from = Double.parseDouble(FromValue.getText());
			
		Transaction transaction = new Transaction(name,phone,ID,address,fromC,toC,from);
		DisplayTA.setText(transaction.toString());
    }//GEN-LAST:event_DisplayTransactionBtnActionPerformed

    private void DisplayAllTransactionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayAllTransactionBtnActionPerformed
        // TODO add your handling code here:
        try{
			File inFile = new File("Transactions.txt");
			FileReader fr = new FileReader(inFile);
			BufferedReader br = new BufferedReader(fr);
			DisplayTA.read(br,null);
			br.close();
			DisplayTA.requestFocus();
		}
		catch(IOException e){
			JOptionPane.showMessageDialog(null,"Error writing to file","Error!",JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_DisplayAllTransactionBtnActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        // TODO add your handling code here:
        DisplayTA.setText("");
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void SaveTransactionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveTransactionBtnActionPerformed
        // TODO add your handling code here:
        try{
			FileWriter fw = new FileWriter("Transactions.txt");
			PrintWriter pw = new PrintWriter(fw);
			for(Transaction t: Transaction){
				pw.write(t.toString()+"\n\n");
			}
			fw.close();
			JOptionPane.showMessageDialog(null,"Successfully written to file","Done!",JOptionPane.INFORMATION_MESSAGE);
		}
		catch(IOException e){
			JOptionPane.showMessageDialog(null,"Error writing to file","Error!",JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_SaveTransactionBtnActionPerformed

    private void DisplayTodaysTransactionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayTodaysTransactionBtnActionPerformed
        // TODO add your handling code here:
        for(Transaction t:Transaction){
            DisplayTA.append(t.toString()+"\n\n");
		}
    }//GEN-LAST:event_DisplayTodaysTransactionBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTransactionBtn;
    private javax.swing.JTextField AddressTF;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton DisplayAllTransactionBtn;
    private javax.swing.JTextArea DisplayTA;
    private javax.swing.JButton DisplayTodaysTransactionBtn;
    private javax.swing.JButton DisplayTransactionBtn;
    private javax.swing.JComboBox<String> FromCurrency;
    private javax.swing.JTextField FromValue;
    private javax.swing.JTextField ICTF;
    private javax.swing.JTextField NameTF;
    private javax.swing.JTextField PhoneTF;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JButton SaveTransactionBtn;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JComboBox<String> ToCurrency;
    private javax.swing.JTextField ToValue;
    private javax.swing.JTextField deletenum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchnum;
    // End of variables declaration//GEN-END:variables
}
